### PR TITLE
fix(ci): try another caching mechanism

### PR DESCRIPTION
**Pull request by redox**
I don't see where the `maven: true` option is documented, this seems to be the way to do it.

### CODE REVIEW

**Review by ElPicador — APPROVED** [review]

**Comment by ElPicador** [comment]
@redox I think you went a bit too far for this one 😛 .
The removal of the `waitForCompletion` will be easier after the resolution of this issue: https://github.com/algolia/algoliasearch-client-java-2/issues/439

**Comment by redox** [comment]
> @redox I think you went a bit too far for this one 😛 .
> The removal of the waitForCompletion will be easier after the resolution of this issue: #439

Yeah maybe :) But you got my point, I'll let you handle #439 and then see how this one will go!

**Comment by ElPicador** [comment]
Closing in favor of #450

**Comment by redox** [comment]
> Closing in favor of #450

I think 4c63113054866f8ffbd847dc2e278e3494854bc5 is still worth cherry-picking @ElPicador, isn't it?

**Comment by ElPicador** [comment]
Yes it's on my TODO list :)

Le jeu. 18 janv. 2018 à 13:56, Sylvain Utard <notifications@github.com> a
écrit :

**Pull request closed without merging**
