### PR TITLE
Added queryid field to SearchResult

### PR DESCRIPTION
**Pull request by sunnymattas**
| Q                 | A
| ----------------- | ----------
| Bug fix?          |  yes
| New feature?      | no   
| BC breaks?        | no     
| Need Doc update   | no

## What was changed
 queryid field has been added to SearchResult class. 

## Why it was changed
Queryid field value is returned with search results when  query has parameter  clickAnalytics = true. QueryId value is used to capture click +rates and conversions.

### CODE REVIEW

**Comment by julienbourdeau** [comment]
Hi @sunnymattas,

Thanks for your contribution! I'll try to add a test case this afternoon and we can release it. 👍

**Comment by sunnymattas** [comment]
Hi Julien,
When you would be able to merge this PR? Thanks.

**Review by julienbourdeau — APPROVED** [review]

**Comment by julienbourdeau** [comment]
@sunnymattas I'll release the client with your change tomorrow :) Thanks for your contribution!

**Comment by sunnymattas** [comment]
@julienbourdeau thanks for merging PR. When you think this version of jar would be published. I am still getting 2.16.8. Thanks.

**Comment by wietsevenema** [comment]
@ElPicador I think the release is stuck again, I'm still seeing 2.16.8 in maven central?

**Comment by ElPicador** [comment]
Seems maven central has some issue. The 2.17.1 should be available soon (we released it on friday :/)

**Pull request merged**
